### ISSUE TITLE
Error running python application

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/appstart#15]
I'm trying to run an app using `appstart run app.yaml`, it's throwing errors on startup.
- clone the samples repo

``` sh
git clone https://github.com/GoogleCloudPlatform/python-docs-samples/
cd appengine/angular/
echo "FROM gcr.io/google_appengine/python-compat" > Dockerfile
```
- Open app.yaml, and add `vm:true`
- run `appstart run app.yaml`

I've tried this with a few python apps.  I always get this error. 

beckwith-macbookpro:angular beckwith$ appstart run app.yaml
[I: 14:02:51] -------------------------------  BUILDING IMAGE  -------------------------------
[I: 14:02:51] IMAGE  : devappserver_image.2015.10.26_14.02.51
[I: 14:02:51] Step 0 : FROM appstart_devappserver_base
[I: 14:02:51] ---> 32a9be320770
[I: 14:02:51] Step 1 : ADD /Users/beckwith/Code/python-docs-samples/appengine/angular/\* /app/
[I: 14:02:51] ---> c605c6b014a7
[I: 14:02:51] Removing intermediate container 2eff66ac9fcf
[I: 14:02:51] Successfully built c605c6b014a7
[I: 14:02:51] --------------------------------------------------------------------------------
[I: 14:02:52] Starting container: devappserver.2015.10.26_14.02.51
[I: 14:02:52] Starting container: devappserver.2015.10.26_14.02.51
[I: 14:02:52] -------------------------------  BUILDING IMAGE  -------------------------------
[I: 14:02:52] IMAGE  : app_image.2015.10.26_14.02.51
[I: 14:02:52] Step 0 : FROM gcr.io/google_appengine/python-compat
[I: 14:02:52] ---> c12fedbf16c3
[I: 14:02:52] Successfully built c12fedbf16c3
[I: 14:02:52] --------------------------------------------------------------------------------
[I: 14:02:52] Starting container: test_app.2015.10.26_14.02.51
[I: 14:02:52] Starting container: pinger.2015.10.26_14.02.51
[I: 14:02:52] Waiting for application to listen on port 8080
Waiting .[D: 14:02:53] LOG 1 1445893373757486 Using module_yaml_path from env: app.yaml
[D: 14:02:53] Traceback (most recent call last):
[D: 14:02:53] File "/home/vmagent/python_vm_runtime/vmboot.py", line 133, in <module>
[D: 14:02:53] run_file(**file**, globals())
[D: 14:02:53] File "/home/vmagent/python_vm_runtime/vmboot.py", line 129, in run_file
[D: 14:02:53] execfile(_PATHS.script_file(script_name), globals_)
[D: 14:02:53] File "/home/vmagent/python_vm_runtime/google/appengine/tools/vmboot.py", line 65, in <module>
[D: 14:02:53] main()
[D: 14:02:53] File "/home/vmagent/python_vm_runtime/google/appengine/tools/vmboot.py", line 61, in main
[D: 14:02:53] vmservice.CreateAndRunService(module_yaml_path)
[D: 14:02:53] File "/home/vmagent/python_vm_runtime/google/appengine/ext/vmruntime/vmservice.py", line 154, in CreateAndRunService
[D: 14:02:53] service.CreateServer()
[D: 14:02:53] File "/home/vmagent/python_vm_runtime/google/appengine/ext/vmruntime/vmservice.py", line 123, in CreateServer
[D: 14:02:53] with open(self.filename) as stream:
[D: 14:02:53] IOError: [Errno 2] No such file or directory: 'app.yaml'
[D: 14:02:53] 
[I: 14:02:54] Stopping 7e39663371b96cc4fba9d382bf6abadea316f55891cbe5a6343e7da95c5c4ed7
[I: 14:02:54] Removing 7e39663371b96cc4fba9d382bf6abadea316f55891cbe5a6343e7da95c5c4ed7
[I: 14:02:54] Stopping c8904cb9f7fb6b7a4c72ebf7264422db92dbbe53ad605204858d83a37f7b69b4
[I: 14:02:54] Removing c8904cb9f7fb6b7a4c72ebf7264422db92dbbe53ad605204858d83a37f7b69b4
[W: 14:02:54] test_app.2015.10.26_14.02.51 stopped prematurely
beckwith-macbookpro:angular beckwith$

**Comment by JustinBeckwith** [comment]
I forgot to add the app to the container. _hangs head in shame_
